services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=conferences-test'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/conferences-test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge